// LINQPad Program

// For LINQPad Premium edition users, here's a walkthrough to demonstrate advanced code completion and fixes.

void Main()
{
	// 1. Move the cursor to the line below and press Alt+Enter (Option-Return on macOS) to generate SomeNewMethod.		
	SomeNewMethod ("foo", 123, true);
	
	// 2. Press Alt+Enter again to generate a constructor for Foo.
	new Foo (title:"Autogenerated", count:123);

	// 3. Press Alt+Enter again to import 'System.Windows.Controls' and reference 'PresentationFramework.dll'
	new TextBox().Dump();
}

class Foo : MyBase, IEquatable<Foo>     // 4. Keep pressing Alt+Enter to implement MyBase and IEquatable<T>
{
}

abstract class MyBase
{
	public abstract string SomeMethod (DateTime dt, int x, bool flag);
}

// 5. Finally, type 'override ' into the Foo class to override the Equals or ToString method.